{% set name = "iam-units" %}
{% set name_ = "iam_units" %}
{% set version = "2023.9.12" %}
{% set hash = "89cfbcf5ab88d0dfd0b0639cabffe29ddf9f967f851184b3f3d86cd5ba7f43c9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - pint

test:
  imports:
    - iam_units
    - iam_units.emissions

about:
  home: https://github.com/IAMconsortium/units
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Unit definitions for integrated-assessment research
  description: |
    Pint-compatible definitions of energy, climate, and related units, to
    supplement the SI and other units included in Pint's default_en.txt.

extra:
  recipe-maintainers:
    - danielhuppmann
    - khaeru
