{% set name = "iam-units" %}
{% set name_ = "iam_units" %}
{% set version = "2021.3.22" %}
{% set hash = "96cee98b40b763560b24bfdd389174a4561de4fe85bdff59fdbd94cf2b4c5f7d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools-scm
  run:
    - python
    - pint

test:
  imports:
    - iam_units
    - iam_units.emissions

about:
  home: https://github.com/IAMconsortium/units
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Unit definitions for integrated-assessment research
  description: |
    Pint-compatible definitions of energy, climate, and related units, to
    supplement the SI and other units included in Pint's default_en.txt.

extra:
  recipe-maintainers:
    - khaeru
